### PR TITLE
Adds support for embedded-hal v1.0.0-alpha.8 traits

### PR DESCRIPTION
**Pull request by almindor**
Adds support for the alpha.8 of v1.0.0 embedded-hal for SPI

I don't have I2C to test those changes

### CODE REVIEW

**Comment by therealprof** [comment]
Looks good to me. Are you planning more changes or should we just go for it?

**Comment by almindor** [comment]
> Looks good to me. Are you planning more changes or should we just go for it?

Yes, but I'm unsure of the release mode. I don't think this should go to master until embedded-hal v1.0 is out of alpha. We could merge it into a branch and do crates pre-release so people can use that version easier (similar to how embedded-hal alpha pre-releases are pushed out)

**Comment by therealprof** [comment]
I'm not really worried at all, we could even release it as an alpha; pre-releases are not automatically picked up by cargo so nothing should break.

**Comment by almindor** [comment]
> I'm not really worried at all, we could even release it as an alpha; pre-releases are not automatically picked up by cargo so nothing should break.

Ok :) I'll let you punch it.

**Review by therealprof — APPROVED** [review]
LGTM, thanks.

**Comment by bindermuehle** [comment]
I'm not quite sure what release procedures are used. I just wanted to inform you that the 0.5.0-alpha.1 version has not been release to cargo yet.

**Pull request merged**
