### PR TITLE
Add defmt feature: derive Format for DisplayError

### PR DESCRIPTION
**Pull request by barafael**

### CODE REVIEW

**Comment by therealprof** [comment]
How on earth did you manage to get conflicts with a fresh PR? 😅

**Comment by barafael** [comment]
Lol sry, I'm gonna fix it :D I used this branch for weeks not realising that I never pr'd it.

**Comment by therealprof** [comment]
Hm, you closed it? 😅

**Comment by barafael** [comment]
superseded by: #41

**Pull request closed without merging**
